# Generated by Django 4.2 on 2024-07-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
