# Generated by Django 4.2 on 2024-07-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_token_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='name',
        ),
        migrations.AddField(
            model_name='token',
            name='long_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='token',
            name='short_name',
            field=models.CharField(default='', max_length=16),
        ),
    ]
