# Generated by Django 4.2 on 2024-07-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_token_name_token_long_name_token_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenInWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_in_wallet', to='api.token')),
            ],
        ),
        migrations.AlterField(
            model_name='wallet',
            name='tokens',
            field=models.ManyToManyField(related_name='wallet', to='api.tokeninwallet'),
        ),
    ]
