# Generated by Django 4.2 on 2024-07-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_tokeninwallet_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokeninwallet',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='api.wallet'),
        ),
    ]
