# Generated by Django 4.2 on 2024-08-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenHistory',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.token')),
            ],
            bases=('api.token',),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
