# Generated by Django 4.2 on 2024-08-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_wallet_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
