# Generated by Django 4.2 on 2024-08-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='token',
        ),
    ]
