# Generated by Django 4.2.9 on 2024-08-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='check_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
