# Generated by Django 4.2.9 on 2024-08-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_token_check_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='check_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
