# Generated by Django 4.2.9 on 2024-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_token_check_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokeninwallet',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
