# Generated by Django 4.2.9 on 2024-08-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_tokeninwallet_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenHistory',
        ),
    ]
