# Generated by Django 4.2.9 on 2024-08-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_tokenhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', max_length=16)),
                ('long_name', models.CharField(default='', max_length=128)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('check_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
