# Generated by Django 4.2.9 on 2024-08-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_tokenhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenhistory',
            name='check_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
